50App/Hot371.Site.Enterprise/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hot371.Site.Enterprise.Controllers
{
    public class AccountController : Controller
    {
        //
        // GET: /Account/

        public ActionResult Login()
        {
            return View();
        }

    }
}

50App/Hot371.Site.Enterprise/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCBase.Component.QRCode;

namespace Hot371.Site.Enterprise.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            //var stream = QRCodeGenerate.BuildQrCode(@"http://m.ly.com", QrCodeLevel.H);
            //return File(stream, @"image/jpeg");
            return View();
        }

    }
}

50App/Hot371.Site.Enterprise/Controllers/PositionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hot371.Site.Enterprise.Controllers
{
    public class PositionController : Controller
    {
        //
        // GET: /Position/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }
    }
}

50App/Hot371.Site.Enterprise/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

50App/Hot371.Site.Enterprise/Views/Position/Add.cshtml
@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

50App/Hot371.Site.Enterprise/Views/Position/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-inline">
            <div class="form-group">
                <label for="exampleInputEmail2">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label>Password</label>
                <select class="form-control">
                    <option>Option 1</option>
                    <option>Option 2</option>
                    <option>Option 3</option>
                </select>
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox"> Remember me
                </label>
            </div>
            <button type="submit" class="btn btn-primary">查 询</button>
            @Html.ActionLink("新 增", "Add", "Position", null, new { @class = "btn btn-success" })
        </form>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th style="width:10%;">活动期数</th>
                <th style="width:20%;">标题</th>
                <th style="width:28%;">描述</th>
                <th>开始日期</th>
                <th>结束日期</th>
                <th style="width:5%;">状态</th>
                <th>创建日期</th>
                <th style="width:5%;">操作</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    @Html.ActionLink("修改", "Index", "Position", new { id = 1 }, new { @class = "btn btn-info btn-xs" })
                </td>
            </tr>
        </tbody>
    </table>

    <div class="panel panel-footer">

    </div>
</div>

50App/Hot371.Site.Enterprise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Styles/style.default.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Styles/jquery.datatables.css")" rel="stylesheet" />
    @RenderSection("styles", required: false)
</head>
    <body>
        <!-- Preloader -->
        <div id="preloader">
            <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
        </div>
        
        <section>
            <div class="leftpanel">

                <div class="logopanel">
                    <h1><span>[</span> bracket <span>]</span></h1>
                </div><!-- logopanel -->
                <div class="leftpanelinner">
                    <h5 class="sidebartitle">Navigation</h5>
                    <ul class="nav nav-pills nav-stacked nav-bracket">
                        <li class="active"><a href="index.html"><i class="fa fa-home"></i> <span>Dashboard</span></a></li>
                        <li><a href="email.html"><i class="fa fa-envelope-o"></i> <span>Email</span></a></li>
                        <li class="nav-parent">
                            <a href=""><i class="fa fa-edit"></i> <span>Forms</span></a>
                            <ul class="children">
                                <li><a href="general-forms.html"><i class="fa fa-caret-right"></i> General Forms</a></li>
                                <li><a href="form-layouts.html"><i class="fa fa-caret-right"></i> Form Layouts</a></li>
                                <li><a href="form-validation.html"><i class="fa fa-caret-right"></i> Form Validation</a></li>
                                <li><a href="form-wizards.html"><i class="fa fa-caret-right"></i> Form Wizards</a></li>
                                <li><a href="wysiwyg.html"><i class="fa fa-caret-right"></i> WYSIWYG</a></li>
                            </ul>
                        </li>
                        <li class="nav-parent">
                            <a href=""><i class="fa fa-suitcase"></i> <span>UI Elements</span></a>
                            <ul class="children">
                                <li><a href="buttons.html"><i class="fa fa-caret-right"></i> Buttons</a></li>
                                <li><a href="icons.html"><i class="fa fa-caret-right"></i> Icons</a></li>
                                <li><a href="typography.html"><i class="fa fa-caret-right"></i> Typography</a></li>
                                <li><a href="alerts.html"><i class="fa fa-caret-right"></i> Alerts &amp; Notifications</a></li>
                                <li><a href="tabs-accordions.html"><i class="fa fa-caret-right"></i> Tabs &amp; Accordions</a></li>
                                <li><a href="sliders.html"><i class="fa fa-caret-right"></i> Sliders</a></li>
                                <li><a href="graphs.html"><i class="fa fa-caret-right"></i> Graphs &amp; Charts</a></li>
                                <li><a href="widgets.html"><i class="fa fa-caret-right"></i> Panels &amp; Widgets</a></li>
                                <li><a href="extras.html"><i class="fa fa-caret-right"></i> Extras</a></li>
                            </ul>
                        </li>
                        <li><a href="tables.html"><i class="fa fa-th-list"></i> <span>Tables</span></a></li>
                        <li><a href="maps.html"><i class="fa fa-map-marker"></i> <span>Maps</span></a></li>
                        <li class="nav-parent">
                            <a href=""><i class="fa fa-file-text"></i> <span>Pages</span></a>
                            <ul class="children">
                                <li><a href="calendar.html"><i class="fa fa-caret-right"></i> Calendar</a></li>
                                <li><a href="media-manager.html"><i class="fa fa-caret-right"></i> Media Manager</a></li>
                                <li><a href="timeline.html"><i class="fa fa-caret-right"></i> Timeline</a></li>
                                <li><a href="blog-list.html"><i class="fa fa-caret-right"></i> Blog List</a></li>
                                <li><a href="blog-single.html"><i class="fa fa-caret-right"></i> Blog Single</a></li>
                                <li><a href="people-directory.html"><i class="fa fa-caret-right"></i> People Directory</a></li>
                                <li><a href="profile.html"><i class="fa fa-caret-right"></i> Profile</a></li>
                                <li><a href="invoice.html"><i class="fa fa-caret-right"></i> Invoice</a></li>
                                <li><a href="search-results.html"><i class="fa fa-caret-right"></i> Search Results</a></li>
                                <li><a href="blank.html"><i class="fa fa-caret-right"></i> Blank Page</a></li>
                                <li><a href="notfound.html"><i class="fa fa-caret-right"></i> 404 Page</a></li>
                                <li><a href="locked.html"><i class="fa fa-caret-right"></i> Locked Screen</a></li>
                                <li><a href="signin.html"><i class="fa fa-caret-right"></i> Sign In</a></li>
                                <li><a href="signup.html"><i class="fa fa-caret-right"></i> Sign Up</a></li>
                            </ul>
                        </li>
                        <li><a href="layouts.html"><i class="fa fa-laptop"></i> <span>Skins &amp; Layouts</span></a></li>
                    </ul>
                </div>
            </div><!-- leftpanel -->

            <div class="mainpanel">
                <div class="headerbar">
                    <a class="menutoggle"><i class="fa fa-bars"></i></a>
                    
                    <div class="header-right">
                        <ul class="headermenu">
                            <li>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                        <img src="../Images/photos/loggeduser.png" alt="" />
                                        John Doe
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-usermenu pull-right">
                                        <li><a href="profile.html"><i class="glyphicon glyphicon-user"></i> My Profile</a></li>
                                        <li><a href="#"><i class="glyphicon glyphicon-cog"></i> Account Settings</a></li>
                                        <li><a href="#"><i class="glyphicon glyphicon-question-sign"></i> Help</a></li>
                                        <li><a href="signin.html"><i class="glyphicon glyphicon-log-out"></i> Log Out</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div><!-- header-right -->
                </div>
                
                <div class="pageheader">
                    <h2><i class="fa fa-home"></i> Dashboard </h2>
                </div>
            
                <div class="contentpanel">
                    @RenderBody()
                </div>
            </div><!-- mainpanel -->
            

        </section>
        
        <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery-migrate-1.2.1.min.js")"></script>
        <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
        <script src="@Url.Content("~/Scripts/modernizr.min.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery.sparkline.min.js")"></script>
        <script src="@Url.Content("~/Scripts/toggles.min.js")"></script>
        <script src="@Url.Content("~/Scripts/retina.min.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery.cookies.js")"></script>

        <script src="@Url.Content("~/Scripts/flot/flot.min.js")"></script>
        <script src="@Url.Content("~/Scripts/flot/flot.resize.min.js")"></script>
        <script src="@Url.Content("~/Scripts/morris.min.js")"></script>
        <script src="@Url.Content("~/Scripts/raphael-2.1.0.min.js")"></script>

        <script src="@Url.Content("~/Scripts/jquery.datatables.min.js")"></script>
        <script src="@Url.Content("~/Scripts/chosen.jquery.min.js")"></script>

        <script src="@Url.Content("~/Scripts/custom.js")"></script>
        <script src="@Url.Content("~/Scripts/dashboard.js")"></script>
        
        @RenderSection("scripts", required: false)
    </body>
</html>